name: Build Mod

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-22.04
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Make Gradle wrapper executable
              run: chmod +x ./gradlew
    
            - name: Build with Gradle
              run: ./gradlew build

            - name: Upload built jar
              uses: actions/upload-artifact@v4
              with:
                  name: mod-jar
                  path: build/libs/*.jar
